server:
  port: 8081
girl: 
  cupSize: B
  age: 18
  content: "cupSize: ${cupSize},age: ${age}"
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hyron_test
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true